// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkVT4LWil47RwkIUyzRFI2fcroKle4wTw',
    appId: '1:384640601225:web:a8a5bd4411c3797a314a58',
    messagingSenderId: '384640601225',
    projectId: 'chatapp-eeddd',
    authDomain: 'chatapp-eeddd.firebaseapp.com',
    storageBucket: 'chatapp-eeddd.firebasestorage.app',
    measurementId: 'G-9MQGSQBKKN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvcZzu5Kw7hz85oauVOnKh34lHLYIUh5E',
    appId: '1:384640601225:android:25c2c7a05b396559314a58',
    messagingSenderId: '384640601225',
    projectId: 'chatapp-eeddd',
    storageBucket: 'chatapp-eeddd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPwSlaMGoVCSOi8JUO1do0hysR2D06AuQ',
    appId: '1:384640601225:ios:e2332af500e6dd4e314a58',
    messagingSenderId: '384640601225',
    projectId: 'chatapp-eeddd',
    storageBucket: 'chatapp-eeddd.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPwSlaMGoVCSOi8JUO1do0hysR2D06AuQ',
    appId: '1:384640601225:ios:e2332af500e6dd4e314a58',
    messagingSenderId: '384640601225',
    projectId: 'chatapp-eeddd',
    storageBucket: 'chatapp-eeddd.firebasestorage.app',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkVT4LWil47RwkIUyzRFI2fcroKle4wTw',
    appId: '1:384640601225:web:e118b9b6e366ccb3314a58',
    messagingSenderId: '384640601225',
    projectId: 'chatapp-eeddd',
    authDomain: 'chatapp-eeddd.firebaseapp.com',
    storageBucket: 'chatapp-eeddd.firebasestorage.app',
    measurementId: 'G-CNJHPXPFW4',
  );
}
